version: 2
build:
  image: "readthedocs/sphinx-build:latest"
  os: "ubuntu-20.04"
  commands:
    - sphinx-build -b html -d _build/doctrees . _build/html  # Sphinx build command

python:
  install:
    - method: pip
      extra_index_url: "https://581351078906.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/"
<<<<<<< HEAD
      requirements: requirements.txt
  sphinx:
  configuration: conf.py
=======
    - requirements: "requirements.txt"
>>>>>>> 225e6a4dddfa69507d635281a25bc590f4f368d2
