version: 2
build:
  image: "readthedocs/sphinx-build:latest"
  os: "ubuntu-20.04"
python:
  install:
    - method: pip  # Use pip for installing dependencies
      extra_index_url: "https://581351078906.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/"
    - requirements: "requirements.txt"  # Make sure the path to your requirements.txt is correct
