version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"  # Use your desired Python version

python:
  install:
    - method: pip
      requirements: requirements.txt

sphinx:
  configuration: conf.py
