version: 2

build:
  os: ubuntu-latest
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

build:
  commands:
    - sphinx-build -b html -d $READTHEDOCS_OUTPUT/doctrees . $READTHEDOCS_OUTPUT/html


