version: 2
build:
  image: "readthedocs/sphinx-build:latest"
  os: "ubuntu-20.04"  # Or another valid Ubuntu version
python:
  install:
    - method: pip
      extra_index_url: "https://581351078906.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/"
