version: 2
build:
  image: "readthedocs/sphinx-build:latest"
  os: "ubuntu-20.04"
  commands:
    - sphinx-build -b html -d _build/doctrees . _build/html  # Sphinx build command
python:
  install:
    requirements: "requirements.txt"  # Correctly reference the requirements.txt
    extra_index_url: "https://581351078906.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/"

