
# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04  # Specify the operating system
  tools:
    python: "3.10"  # Specify the Python version

# Define Python requirements
python:
  install:
    - requirements: requirements.txt

# Build documentation with Sphinx
sphinx:
  configuration: conf.py



