# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04  # Specify the operating system
  tools:
    python: "3.10"  # Specify the Python version
  commands:
    - pip install requirements.txt
    - python get_codeartifact_token.py

# Build documentation with Sphinx
sphinx:
  configuration: conf.py

